
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoJSON extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return TokenJson.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoJSON() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoJSON(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoJSON(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\006\000\002\002\004\000\002\002\005\000\002\004" +
    "\005\000\002\004\003\000\002\003\005\000\002\003\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\004\004\004\001\002\000\004\006\011\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\006\005\016\011\015\001\002\000\006\005\ufffe\011" +
    "\ufffe\001\002\000\004\010\012\001\002\000\006\006\014" +
    "\007\013\001\002\000\006\005\ufffc\011\ufffc\001\002\000" +
    "\006\005\ufffd\011\ufffd\001\002\000\004\006\011\001\002" +
    "\000\004\002\000\001\002\000\006\005\uffff\011\uffff\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\004\002\004\001\001\000\006\003\007\004" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\016" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoJSON$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoJSON$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoJSON$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    public void syntax_error(Symbol s){ 
        System.out.println("Error Sintáctico en la Línea " + (s.left) +
        " Columna "+s.right+ ". No se esperaba este componente: " +s.value+"."); 
    } 

    
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error síntactico irrecuperable en la Línea " + 
        (s.left)+ " Columna "+s.right+". Componente " + s.value + 
        " no reconocido."); 
    }  


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoJSON$actions {
  private final SintacticoJSON parser;

  /** Constructor */
  CUP$SintacticoJSON$actions(SintacticoJSON parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoJSON$do_action_part00000000(
    int                        CUP$SintacticoJSON$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoJSON$parser,
    java.util.Stack            CUP$SintacticoJSON$stack,
    int                        CUP$SintacticoJSON$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoJSON$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoJSON$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoJSON$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoJSON$parser.done_parsing();
          return CUP$SintacticoJSON$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= BRAIZQ listainstrucciones BRADER 
            {
              Object RESULT =null;

              CUP$SintacticoJSON$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), RESULT);
            }
          return CUP$SintacticoJSON$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // listainstrucciones ::= listainstrucciones COMA instruccion 
            {
              Object RESULT =null;

              CUP$SintacticoJSON$result = parser.getSymbolFactory().newSymbol("listainstrucciones",2, ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), RESULT);
            }
          return CUP$SintacticoJSON$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // listainstrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$SintacticoJSON$result = parser.getSymbolFactory().newSymbol("listainstrucciones",2, ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), RESULT);
            }
          return CUP$SintacticoJSON$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= CADENA DOSPTO CADENA 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SintacticoJSON$stack.peek()).value;
		System.out.println("Identificador: "+a.replace("\"", "")+" Cadena: "+b.replace("\"", ""));
              CUP$SintacticoJSON$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), RESULT);
            }
          return CUP$SintacticoJSON$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= CADENA DOSPTO DECIMAL 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$SintacticoJSON$stack.peek()).value;
		System.out.println("Identificador: "+a.replace("\"", "")+" Cadena: "+b);
              CUP$SintacticoJSON$result = parser.getSymbolFactory().newSymbol("instruccion",1, ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.elementAt(CUP$SintacticoJSON$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJSON$stack.peek()), RESULT);
            }
          return CUP$SintacticoJSON$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoJSON$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoJSON$do_action(
    int                        CUP$SintacticoJSON$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoJSON$parser,
    java.util.Stack            CUP$SintacticoJSON$stack,
    int                        CUP$SintacticoJSON$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoJSON$do_action_part00000000(
                               CUP$SintacticoJSON$act_num,
                               CUP$SintacticoJSON$parser,
                               CUP$SintacticoJSON$stack,
                               CUP$SintacticoJSON$top);
    }
}

}
