
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEWVAL = 20;
  public static final int MENOS = 24;
  public static final int BRADER = 3;
  public static final int IDENT = 10;
  public static final int CADENA = 4;
  public static final int DOLAR = 21;
  public static final int IGUAL = 11;
  public static final int INT = 16;
  public static final int DEFGLOB = 12;
  public static final int DECIMAL = 5;
  public static final int DIVIDIDO = 26;
  public static final int GRAFBAR = 13;
  public static final int PARIZQ = 9;
  public static final int PARDER = 8;
  public static final int POR = 25;
  public static final int COMA = 22;
  public static final int STRING = 18;
  public static final int EOF = 0;
  public static final int MAIN = 7;
  public static final int error = 1;
  public static final int GRAFPI = 14;
  public static final int PTOCOMA = 15;
  public static final int ENTERO = 19;
  public static final int VOID = 6;
  public static final int MAS = 23;
  public static final int DOUBLE = 17;
  public static final int BRAIZQ = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRAIZQ",
  "BRADER",
  "CADENA",
  "DECIMAL",
  "VOID",
  "MAIN",
  "PARDER",
  "PARIZQ",
  "IDENT",
  "IGUAL",
  "DEFGLOB",
  "GRAFBAR",
  "GRAFPI",
  "PTOCOMA",
  "INT",
  "DOUBLE",
  "STRING",
  "ENTERO",
  "NEWVAL",
  "DOLAR",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO"
  };
}

