
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class TokenJson {
  /* terminals */
  public static final int COMA = 7;
  public static final int DOSPTO = 6;
  public static final int BRADER = 3;
  public static final int error = 1;
  public static final int BRAIZQ = 2;
  public static final int DECIMAL = 5;
  public static final int EOF = 0;
  public static final int CADENA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BRAIZQ",
  "BRADER",
  "CADENA",
  "DECIMAL",
  "DOSPTO",
  "COMA"
  };
}

